version: '3'

services:
  traefik:
    image: traefik:2.8
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=isahara86@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      #      - "--metrics.prometheus=true"
      #      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.watch"
    labels:
      #      - "traefik.http.routers.traefik.service=api@internal"
      #      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
      #      - "traefik.http.routers.traefik.entrypoints=https"
      ###
      #      - "traefik.http.routers.traefik.middlewares=traefik"
      #      - "traefik.http.middlewares.traefik.basicauth.users=admin:$$apr1$$69ymx./1$$i3u8VP2hZdfiNqBIdddcy."
      ##
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      #hsts
      # - "traefik.http.middlewares.hsts-header.headers.stsSeconds=15552000"
      # - "traefik.http.middlewares.hsts-header.headers.stsIncludeSubdomains=true"
      # - "traefik.http.middlewares.hsts-header.headers.stsPreload=true"
      # - "traefik.http.middlewares.hsts-header.headers.forceSTSHeader=true"
      # - "traefik.http.routers.catchall.middlewares=hsts-header"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    restart: on-failure
    networks:
      - my-network

networks:

  my-network:
    external: true
