version: '3.8'

services:


  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    links:
      - db
#    volumes:
#      - ./tmp/logs/:/var/logs
    container_name: nodejs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3000:3000"

# service name should be the same as in env.prod to allow prisma properly generate
  db:
    image: postgres:13
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarian-db
    volumes:
      - ./tmp/db/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
